### ISSUE TITLE
Keşfet 

### ISSUE THREAD

**Issue by yusufalicezik** [yusufalicezik/Impoort-IOS#7]

**Comment by canadmin** [comment]
İçerik henüz net değil.

**Comment by yusufalicezik** [comment]
https://github.com/rubygarage/collection-view-layouts
Kullanılacak keşfet layout türü seç.

**Comment by canadmin** [comment]
Ben IOS geliştirici değilim. Bu yüzden daha uygun birisine atayalım.

**Comment by ridvankabak** [comment]
[https://www.youtube.com/watch?v=K9PZE136hx4](url)
